import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'mr' | 'ta' | 'te' | 'bn' | 'kn' | 'ml' | 'pa' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    hero_title: 'Grow Your Business with AI Power',
    hero_subtitle: 'WhatsApp CRM, Marketing Automation, AI Content — All in One Platform',
    hero_cta: 'Start Free Trial',
    hero_cta2: 'Watch Demo',
    features_title: 'Everything You Need',
    feature1_title: 'WhatsApp Business API',
    feature1_desc: 'Send bulk messages, auto-replies, and chatbot flows',
    feature2_title: 'AI Content Generator',
    feature2_desc: 'Create captions, posts, and marketing content with AI',
    feature3_title: 'Smart CRM',
    feature3_desc: 'Manage contacts, leads, and customer relationships',
    feature4_title: 'Marketing Automation',
    feature4_desc: 'Email campaigns, SMS blasts, and social media scheduling',
    feature5_title: 'E-Commerce Store',
    feature5_desc: 'Product catalog, checkout, and payment links',
    feature6_title: 'Analytics & Reports',
    feature6_desc: 'Track ROI, campaign performance, and business insights',
    pricing_title: 'Simple, Transparent Pricing',
    pricing_free: 'Free',
    pricing_free_price: '₹0/mo',
    pricing_pro: 'Professional',
    pricing_pro_price: '₹999/mo',
    pricing_enterprise: 'Enterprise',
    pricing_enterprise_price: '₹4,999/mo',
    cta_title: 'Ready to Grow?',
    cta_subtitle: 'Join 10,000+ businesses using BizzAuto',
    cta_button: 'Get Started Free',
    nav_features: 'Features',
    nav_pricing: 'Pricing',
    nav_login: 'Login',
    nav_signup: 'Sign Up',
  },
  hi: {
    hero_title: 'AI से अपने व्यवसाय को बढ़ाएं',
    hero_subtitle: 'WhatsApp CRM, मार्केटिंग ऑटोमेशन, AI कंटेंट — सब एक प्लेटफॉर्म पर',
    hero_cta: 'मुफ्त शुरू करें',
    hero_cta2: 'डेमो देखें',
    features_title: 'आपको सब कुछ चाहिए',
    feature1_title: 'WhatsApp Business API',
    feature1_desc: 'बल्क मैसेज, ऑटो-रिप्लाई और चैटबॉट भेजें',
    feature2_title: 'AI कंटेंट जनरेटर',
    feature2_desc: 'AI से कैप्शन, पोस्ट और मार्केटिंग कंटेंट बनाएं',
    feature3_title: 'स्मार्ट CRM',
    feature3_desc: 'संपर्क, लीड और ग्राहक संबंध प्रबंधित करें',
    feature4_title: 'मार्केटिंग ऑटोमेशन',
    feature4_desc: 'ईमेल कैंपेन, SMS और सोशल मीडिया शेड्यूलिंग',
    feature5_title: 'ई-कॉमर्स स्टोर',
    feature5_desc: 'प्रोडक्ट कैटलॉग, चेकआउट और पेमेंट लिंक',
    feature6_title: 'एनालिटिक्स और रिपोर्ट',
    feature6_desc: 'ROI, कैंपेन परफॉर्मेंस और बिज़नेस इनसाइट्स ट्रैक करें',
    pricing_title: 'सरल, पारदर्शी मूल्य निर्धारण',
    pricing_free: 'मुफ्त',
    pricing_free_price: '₹0/माह',
    pricing_pro: 'पेशेवर',
    pricing_pro_price: '₹999/माह',
    pricing_enterprise: 'एंटरप्राइज',
    pricing_enterprise_price: '₹4,999/माह',
    cta_title: 'बढ़ने के लिए तैयार?',
    cta_subtitle: '10,000+ व्यवसाय BizzAuto का उपयोग कर रहे हैं',
    cta_button: 'मुफ्त शुरू करें',
    nav_features: 'विशेषताएं',
    nav_pricing: 'मूल्य',
    nav_login: 'लॉगिन',
    nav_signup: 'साइन अप',
  },
  mr: {
    hero_title: 'AI शक्तीने आपला व्यवसाय वाढवा',
    hero_subtitle: 'WhatsApp CRM, मार्केटिंग ऑटोमेशन, AI कंटेंट — सर्व एका प्लॅटफॉर्मवर',
    hero_cta: 'मोफत सुरू करा',
    hero_cta2: 'डेमो पहा',
    features_title: 'तुम्हाला सर्व कंपे लागेल',
    feature1_title: 'WhatsApp Business API',
    feature1_desc: 'बल्क मैसेज, ऑटो-रिप्लाई आणि चैटबॉट पाठवा',
    feature2_title: 'AI कंटेंट जनरेटर',
    feature2_desc: 'AI ने कॅप्शन, पोस्ट आणि मार्केटिंग कंटेंट तयार करा',
    feature3_title: 'स्मार्ट CRM',
    feature3_desc: 'संपर्क, लीड आणि ग्राहक संबंध व्यवस्थापित करा',
    feature4_title: 'मार्केटिंग ऑटोमेशन',
    feature4_desc: 'ईमेल कॅम्पेन, SMS आणि सोशल मीडिया शेड्यूलिंग',
    feature5_title: 'ई-कॉमर्स स्टोअर',
    feature5_desc: 'प्रोडक्ट कॅटलॉग, चेकआउट आणि पेमेंट लिंक',
    feature6_title: 'अॅनालिटिक्स आणि अहवाल',
    feature6_desc: 'ROI, कॅम्पेन परफॉर्मन्स आणि बिझनेस इन्साइट्स ट्रॅक करा',
    pricing_title: 'सोपे, पारदर्शक मूल्य निर्धारण',
    pricing_free: 'मोफत',
    pricing_free_price: '₹0/महिना',
    pricing_pro: 'व्यावसायिक',
    pricing_pro_price: '₹999/महिना',
    pricing_enterprise: 'एंटरप्राइज',
    pricing_enterprise_price: '₹4,999/महिना',
    cta_title: 'वाढण्यासाजर?',
    cta_subtitle: '10,000+ व्यवसाय BizzAuto वापरत आहेत',
    cta_button: 'मोफत सुरू करा',
    nav_features: 'वैशिष्ट्ये',
    nav_pricing: 'मूल्य',
    nav_login: 'लॉगिन',
    nav_signup: 'साइन अप',
  },
  ta: {
    hero_title: 'AI ஆற்றலால் உங்கள் வணிகத்தை வளர்க்கவும்',
    hero_subtitle: 'WhatsApp CRM, சந்தைப்படுத்தல் தானியங்குதல், AI உள்ளடக்கம் — எல்லாம் ஒரே தளத்தில்',
    hero_cta: 'இலவசமாக தொடங்கவும்',
    hero_cta2: 'டெமோ பார்க்கவும்',
    features_title: 'உங்களுக்கு தேவையான அனைத்தும்',
    feature1_title: 'WhatsApp Business API',
    feature1_desc: 'மொத்த செய்திகள், தானியங்கு பதில்கள் மற்றும் சாட்போட் அனுப்பவும்',
    feature2_title: 'AI உள்ளடக்க ஜெனரேட்டர்',
    feature2_desc: 'AI மூலம் தலைப்புகள், இடுகைகள் மற்றும் சந்தைப்படுத்தல் உள்ளடக்கத்தை உருவாக்கவும்',
    feature3_title: 'ஸ்மார்ட் CRM',
    feature3_desc: 'தொடர்புகள், லீட்கள் மற்றும் வாடிக்கையாளர் உறவுகளை நிர்வகிக்கவும்',
    feature4_title: 'சந்தைப்படுத்தல் தானியங்குதல்',
    feature4_desc: 'மின்னஞ்சல் பிரச்சாரங்கள், SMS மற்றும் சமூக ஊடக திட்டமிடல்',
    feature5_title: 'மின்-வணிக கடை',
    feature5_desc: 'தயாரிப்பு வகைப்பாடு, செக்அவுட் மற்றும் பணம் செலுத்தும் இணைப்புகள்',
    feature6_title: 'பகுப்பாய்வு மற்றும் அறிக்கைகள்',
    feature6_desc: 'ROI, பிரச்சார செயல்திறன் மற்றும் வணிக நுண்ணறிவுகளை கண்காணிக்கவும்',
    pricing_title: 'எளிய, வெளிப்படையான விலை',
    pricing_free: 'இலவசம்',
    pricing_free_price: '₹0/மாதம்',
    pricing_pro: 'தொழில்முறை',
    pricing_pro_price: '₹999/மாதம்',
    pricing_enterprise: 'நிறுவனம்',
    pricing_enterprise_price: '₹4,999/மாதம்',
    cta_title: 'வளர தயாரா?',
    cta_subtitle: '10,000+ வணிகங்கள் BizzAuto ஐ பயன்படுத்துகின்றன',
    cta_button: 'இலவசமாக தொடங்கவும்',
    nav_features: 'அம்சங்கள்',
    nav_pricing: 'விலை',
    nav_login: 'உள்நுழை',
    nav_signup: 'பதிவு செய்',
  },
  te: {
    hero_title: 'AI శక్తితో మీ వ్యాపారాన్ని పెంచండి',
    hero_subtitle: 'WhatsApp CRM, మార్కెటింగ్ ఆటోమేషన్, AI కంటెంట్ — అన్నీ ఒకే ప్లాట్‌ఫామ్‌లో',
    hero_cta: 'ఉచితంగా ప్రారంభించండి',
    hero_cta2: 'డెమో చూడండి',
    features_title: 'మీకు కావలసినవన్నీ',
    feature1_title: 'WhatsApp Business API',
    feature1_desc: 'బల్క్ మెసేజ్‌లు, ఆటో-రిప్లైలు మరియు చాట్‌బాట్ పంపండి',
    feature2_title: 'AI కంటెంట్ జనరేటర్',
    feature2_desc: 'AI తో క్యాప్షన్లు, పోస్ట్‌లు మరియు మార్కెటింగ్ కంటెంట్ సృష్టించండి',
    feature3_title: 'స్మార్ట్ CRM',
    feature3_desc: 'కాంటాక్ట్‌లు, లీడ్‌లు మరియు కస్టమర్ రిలేషన్షిప్‌లను నిర్వహించండి',
    feature4_title: 'మార్కెటింగ్ ఆటోమేషన్',
    feature4_desc: 'ఇమెయిల్ క్యాంపెయిన్లు, SMS మరియు సోషల్ మీడియా షెడ్యూలింగ్',
    feature5_title: 'ఇ-కామర్స్ స్టోర్',
    feature5_desc: 'ప్రోడక్ట్ కేటలాగ్, చెక్అవుట్ మరియు పేమెంట్ లింక్‌లు',
    feature6_title: 'అనలిటిక్స్ & రిపోర్టులు',
    feature6_desc: 'ROI, క్యాంపెయిన్ పనితీరు మరియు బిజినెస్ ఇన్సైట్స్ ట్రాక్ చేయండి',
    pricing_title: 'సింపుల్, ట్రాన్స్‌పరెంట్ ప్రైసింగ్',
    pricing_free: 'ఉచితం',
    pricing_free_price: '₹0/నెల',
    pricing_pro: 'ప్రొఫెషనల్',
    pricing_pro_price: '₹999/నెల',
    pricing_enterprise: 'ఎంటర్‌ప్రైజ్',
    pricing_enterprise_price: '₹4,999/నెల',
    cta_title: 'పెరగడానికి సిద్ధంగా ఉన్నారా?',
    cta_subtitle: '10,000+ వ్యాపారాలు BizzAuto ఉపయోగిస్తున్నాయి',
    cta_button: 'ఉచితంగా ప్రారంభించండి',
    nav_features: 'ఫీచర్లు',
    nav_pricing: 'ధర',
    nav_login: 'లాగిన్',
    nav_signup: 'సైన్ అప్',
  },
  bn: {
    hero_title: 'AI শক্তি দিয়ে আপনার ব্যবসা বাড়ান',
    hero_subtitle: 'WhatsApp CRM, মার্কেটিং অটোমেশন, AI কনটেন্ট — সব একটি প্ল্যাটফর্মে',
    hero_cta: 'বিনামূল্যে শুরু করুন',
    hero_cta2: 'ডেমো দেখুন',
    features_title: 'আপনার সবকিছু দরকার',
    feature1_title: 'WhatsApp Business API',
    feature1_desc: 'বাল্ক মেসেজ, অটো-রিপ্লাই এবং চ্যাটবট পাঠান',
    feature2_title: 'AI কনটেন্ট জেনারেটর',
    feature2_desc: 'AI দিয়ে ক্যাপশন, পোস্ট এবং মার্কেটিং কনটেন্ট তৈরি করুন',
    feature3_title: 'স্মার্ট CRM',
    feature3_desc: 'যোগাযোগ, লিড এবং গ্রাহক সম্পর্ক পরিচালনা করুন',
    feature4_title: 'মার্কেটিং অটোমেশন',
    feature4_desc: 'ইমেইল ক্যাম্পেইন, SMS এবং সোশ্যাল মিডিয়া শেডিউলিং',
    feature5_title: 'ই-কমার্স স্টোর',
    feature5_desc: 'পণ্য ক্যাটালগ, চেকআউট এবং পেমেন্ট লিঙ্ক',
    feature6_title: 'অ্যানালিটিক্স এবং রিপোর্ট',
    feature6_desc: 'ROI, ক্যাম্পেইন পারফরম্যান্স এবং ব্যবসায়িক অন্তর্দৃষ্টি ট্র্যাক করুন',
    pricing_title: 'সরল, স্বচ্ছ মূল্য নির্ধারণ',
    pricing_free: 'বিনামূল্যে',
    pricing_free_price: '₹0/মাস',
    pricing_pro: 'পেশাদার',
    pricing_pro_price: '₹999/মাস',
    pricing_enterprise: 'এন্টারপ্রাইজ',
    pricing_enterprise_price: '₹4,999/মাস',
    cta_title: 'বাড়তে প্রস্তুত?',
    cta_subtitle: '10,000+ ব্যবসা BizzAuto ব্যবহার করছে',
    cta_button: 'বিনামূল্যে শুরু করুন',
    nav_features: 'বৈশিষ্ট্য',
    nav_pricing: 'মূল্য',
    nav_login: 'লগইন',
    nav_signup: 'সাইন আপ',
  },
  kn: {
    hero_title: 'AI ಶಕ್ತಿಯಿಂದ ನಿಮ್ಮ ವ್ಯವಸಾಯವನ್ನು ಬೆಳೆಸಿ',
    hero_subtitle: 'WhatsApp CRM, ಮಾರ್ಕೆಟಿಂಗ್ ಆಟೋಮೇಷನ್, AI ವಿಷಯ — ಎಲ್ಲವೂ ಒಂದೇ ವೇದಿಕೆಯಲ್ಲಿ',
    hero_cta: 'ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
    hero_cta2: 'ಡೆಮೋ ನೋಡಿ',
    features_title: 'ನಿಮಗೆ ಬೇಕಾದೆಲ್ಲವೂ',
    feature1_title: 'WhatsApp Business API',
    feature1_desc: 'ಬಲ್ಕ್ ಸಂದೇಶಗಳು, ಆಟೋ-ರಿಪ್ಲೈಗಳು ಮತ್ತು ಚಾಟ್‌ಬಾಟ್ ಕಳುಹಿಸಿ',
    feature2_title: 'AI ವಿಷಯ ಜನರೇಟರ್',
    feature2_desc: 'AI ನೊಂದಿಗೆ ಕ್ಯಾಪ್ಷನ್‌ಗಳು, ಪೋಸ್ಟ್‌ಗಳು ಮತ್ತು ಮಾರ್ಕೆಟಿಂಗ್ ವಿಷಯವನ್ನು ರಚಿಸಿ',
    feature3_title: 'ಸ್ಮಾರ್ಟ್ CRM',
    feature3_desc: 'ಸಂಪರ್ಕಗಳು, ಲೀಡ್‌ಗಳು ಮತ್ತು ಗ್ರಾಹಕ ಸಂಬಂಧಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    feature4_title: 'ಮಾರ್ಕೆಟಿಂಗ್ ಆಟೋಮೇಷನ್',
    feature4_desc: 'ಇಮೇಲ್ ಅಭಿಯಾನಗಳು, SMS ಮತ್ತು ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಶೆಡ್ಯೂಲಿಂಗ್',
    feature5_title: 'ಇ-ಕಾಮರ್ಸ್ ಸ್ಟೋರ್',
    feature5_desc: 'ಉತ್ಪಾದನಾ ಕ್ಯಾಟಲಾಗ್, ಚೆಕ್‌ಔಟ್ ಮತ್ತು ಪಾವತಿ ಲಿಂಕ್‌ಗಳು',
    feature6_title: 'ಅನಾಲಿಟಿಕ್ಸ್ & ವರದಿಗಳು',
    feature6_desc: 'ROI, ಅಭಿಯಾನ ಕಾರ್ಯಕ್ಷಮತೆ ಮತ್ತು ವ್ಯವಸಾಯ ಒಳನೋಟಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    pricing_title: 'ಸರಳ, ಪಾರದರ್ಶಕ ಬೆಲೆ',
    pricing_free: 'ಉಚಿತ',
    pricing_free_price: '₹0/ತಿಂಗಳು',
    pricing_pro: 'ವೃತ್ತಿಪರ',
    pricing_pro_price: '₹999/ತಿಂಗಳು',
    pricing_enterprise: 'ಎಂಟರ್‌ಪ್ರೈಸ್',
    pricing_enterprise_price: '₹4,999/ತಿಂಗಳು',
    cta_title: 'ಬೆಳೆಯಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
    cta_subtitle: '10,000+ ವ್ಯವಸಾಯಗಳು BizzAuto ಬಳಸುತ್ತಿವೆ',
    cta_button: 'ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
    nav_features: 'ವೈಶಿಷ್ಟ್ಯಗಳು',
    nav_pricing: 'ಬೆಲೆ',
    nav_login: 'ಲಾಗಿನ್',
    nav_signup: 'ಸೈನ್ ಅಪ್',
  },
  ml: {
    hero_title: 'AI ശക്തി കൊണ്ട് നിങ്ങളുടെ ബിസിനസ് വളർത്തുക',
    hero_subtitle: 'WhatsApp CRM, മാർക്കറ്റിംഗ് ഓട്ടോമേഷൻ, AI ഉള്ളടക്കം — എല്ലാം ഒരു പ്ലാറ്റ്ഫോമിൽ',
    hero_cta: 'സൗജന്യമായി ആരംഭിക്കുക',
    hero_cta2: 'ഡെമോ കാണുക',
    features_title: 'നിങ്ങൾക്ക് ആവശ്യമായതെല്ലാം',
    feature1_title: 'WhatsApp Business API',
    feature1_desc: 'ബൾക്ക് സന്ദേശങ്ങൾ, ഓട്ടോ-റിപ്ലൈകൾ, ചാറ്റ്ബോട്ട് അയയ്ക്കുക',
    feature2_title: 'AI ഉള്ളടക്ക ജനറേറ്റർ',
    feature2_desc: 'AI ഉപയോഗിച്ച് കാപ്ഷനുകളും പോസ്റ്റുകളും മാർക്കറ്റിംഗ് ഉള്ളടക്കവും സൃഷ്ടിക്കുക',
    feature3_title: 'സ്മാർട്ട് CRM',
    feature3_desc: 'കോൺടാക്റ്റുകളും ലീഡുകളും ഉപഭോക്തൃ ബന്ധങ്ങളും നിയന്ത്രിക്കുക',
    feature4_title: 'മാർക്കറ്റിംഗ് ഓട്ടോമേഷൻ',
    feature4_desc: 'ഇമെയിൽ ക്യാമ്പെയിനുകൾ, SMS, സോഷ്യൽ മീഡിയ ഷെഡ്യൂളിംഗ്',
    feature5_title: 'ഇ-കൊമേഴ്‌സ് സ്റ്റോർ',
    feature5_desc: 'ഉൽപ്പന്ന കാറ്റലോഗ്, ചെക്ക്ഔട്ട്, പേയ്‌മെന്റ് ലിങ്കുകൾ',
    feature6_title: 'അനലിറ്റിക്സ് & റിപ്പോർട്ടുകൾ',
    feature6_desc: 'ROI, ക്യാമ്പെയിൻ പ്രകടനം, ബിസിനസ് ഇൻസൈറ്റുകൾ ട്രാക്ക് ചെയ്യുക',
    pricing_title: 'ലളിതവും സുതാര്യവുമായ വില',
    pricing_free: 'സൗജന്യം',
    pricing_free_price: '₹0/മാസം',
    pricing_pro: 'പ്രൊഫഷണൽ',
    pricing_pro_price: '₹999/മാസം',
    pricing_enterprise: 'എന്റർപ്രൈസ്',
    pricing_enterprise_price: '₹4,999/മാസം',
    cta_title: 'വളരാൻ തയ്യാറാണോ?',
    cta_subtitle: '10,000+ ബിസിനസുകൾ BizzAuto ഉപയോഗിക്കുന്നു',
    cta_button: 'സൗജന്യമായി ആരംഭിക്കുക',
    nav_features: 'സവിശേഷതകൾ',
    nav_pricing: 'വില',
    nav_login: 'ലോഗിൻ',
    nav_signup: 'സൈൻ അപ്പ്',
  },
  pa: {
    hero_title: 'AI ਤਾਕਤ ਨਾਲ ਆਪਣਾ ਵਪਾਰ ਵਧਾਓ',
    hero_subtitle: 'WhatsApp CRM, ਮਾਰਕੀਟਿੰਗ ਆਟੋਮੇਸ਼ਨ, AI ਸਮੱਗਰੀ — ਸਭ ਇੱਕ ਪਲੇਟਫਾਰਮ ਤੇ',
    hero_cta: 'ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ',
    hero_cta2: 'ਡੈਮੋ ਵੇਖੋ',
    features_title: 'ਤੁਹਾਨੂੰ ਸਭ ਕੁਝ ਚਾਹੀਦਾ ਹੈ',
    feature1_title: 'WhatsApp Business API',
    feature1_desc: 'ਬਲਕ ਸੁਨੇਹੇ, ਆਟੋ-ਰਿਪਲਾਈ ਅਤੇ ਚੈਟਬੋਟ ਭੇਜੋ',
    feature2_title: 'AI ਸਮੱਗਰੀ ਜਨਰੇਟਰ',
    feature2_desc: 'AI ਨਾਲ ਕੈਪਸ਼ਨ, ਪੋਸਟ ਅਤੇ ਮਾਰਕੀਟਿੰਗ ਸਮੱਗਰੀ ਬਣਾਓ',
    feature3_title: 'ਸਮਾਰਟ CRM',
    feature3_desc: 'ਸੰਪਰਕ, ਲੀਡ ਅਤੇ ਗਾਹਕ ਸੰਬੰਧ ਪ੍ਰਬੰਧਿਤ ਕਰੋ',
    feature4_title: 'ਮਾਰਕੀਟਿੰਗ ਆਟੋਮੇਸ਼ਨ',
    feature4_desc: 'ਈਮੇਲ ਕੈਂਪੇਨ, SMS ਅਤੇ ਸੋਸ਼ਲ ਮੀਡੀਆ ਸ਼ੈਡਿਊਲਿੰਗ',
    feature5_title: 'ਈ-ਕਾਮਰਸ ਸਟੋਰ',
    feature5_desc: 'ਉਤਪਾਦ ਕੈਟਲੌਗ, ਚੈਕਆਉਟ ਅਤੇ ਭੁਗਤਾਨ ਲਿੰਕ',
    feature6_title: 'ਐਨਾਲਿਟਿਕਸ ਅਤੇ ਰਿਪੋਰਟਾਂ',
    feature6_desc: 'ROI, ਕੈਂਪੇਨ ਪ੍ਰਦਰਸ਼ਨ ਅਤੇ ਵਪਾਰਕ ਸੂਝ ਟ੍ਰੈਕ ਕਰੋ',
    pricing_title: 'ਸਧਾਰਨ, ਪਾਰਦਰਸ਼ੀ ਮੁੱਲ',
    pricing_free: 'ਮੁਫ਼ਤ',
    pricing_free_price: '₹0/ਮਹੀਨਾ',
    pricing_pro: 'ਪੇਸ਼ੇਵਰ',
    pricing_pro_price: '₹999/ਮਹੀਨਾ',
    pricing_enterprise: 'ਐਂਟਰਪ੍ਰਾਈਜ਼',
    pricing_enterprise_price: '₹4,999/ਮਹੀਨਾ',
    cta_title: 'ਵਧਣ ਲਈ ਤਿਆਰ?',
    cta_subtitle: '10,000+ ਵਪਾਰ BizzAuto ਵਰਤ ਰਹੇ ਹਨ',
    cta_button: 'ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ',
    nav_features: 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    nav_pricing: 'ਮੁੱਲ',
    nav_login: 'ਲੌਗਇਨ',
    nav_signup: 'ਸਾਈਨ ਅੱਪ',
  },
  gu: {
    hero_title: 'AI શક્તિથી તમારો વ્યવસાય વધારો',
    hero_subtitle: 'WhatsApp CRM, માર્કેટિંગ ઓટોમેશન, AI કન્ટેન્ટ — બધું એક પ્લેટફોર્મ પર',
    hero_cta: 'મફત શરૂ કરો',
    hero_cta2: 'ડેમો જુઓ',
    features_title: 'તમને બધું જોઈએ છે',
    feature1_title: 'WhatsApp Business API',
    feature1_desc: 'બલ્ક સંદેશા, ઓટો-રિપ્લાય અને ચેટબોટ મોકલો',
    feature2_title: 'AI કન્ટેન્ટ જનરેટર',
    feature2_desc: 'AI સાથે કેપ્શન, પોસ્ટ અને માર્કેટિંગ કન્ટેન્ટ બનાવો',
    feature3_title: 'સ્માર્ટ CRM',
    feature3_desc: 'સંપર્કો, લીડ અને ગ્રાહક સંબંધો મેનેજ કરો',
    feature4_title: 'માર્કેટિંગ ઓટોમેશન',
    feature4_desc: 'ઈમેલ કેમ્પેન, SMS અને સોશિયલ મીડિયા શેડ્યુલિંગ',
    feature5_title: 'ઈ-કોમર્સ સ્ટોર',
    feature5_desc: 'પ્રોડક્ટ કેટલોગ, ચેકઆઉટ અને પેમેન્ટ લિંક્સ',
    feature6_title: 'એનાલિટિક્સ અને રિપોર્ટ્સ',
    feature6_desc: 'ROI, કેમ્પેન પર્ફોર્મન્સ અને બિઝનેસ ઈન્સાઈટ્સ ટ્રેક કરો',
    pricing_title: 'સરળ, પારદર્શક કિંમત',
    pricing_free: 'મફત',
    pricing_free_price: '₹0/મહિનો',
    pricing_pro: 'વ્યાવસાયિક',
    pricing_pro_price: '₹999/મહિનો',
    pricing_enterprise: 'એન્ટરપ્રાઈઝ',
    pricing_enterprise_price: '₹4,999/મહિનો',
    cta_title: 'વધવા માટે તૈયાર?',
    cta_subtitle: '10,000+ વ્યવસાયો BizzAuto વાપરી રહ્યા છે',
    cta_button: 'મફત શરૂ કરો',
    nav_features: 'સુવિધાઓ',
    nav_pricing: 'કિંમત',
    nav_login: 'લૉગિન',
    nav_signup: 'સાઈન અપ',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(
    () => (localStorage.getItem('bizzauto-lang') as Language) || 'en'
  );

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('bizzauto-lang', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);

export const languages = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
];